- hosts: postgresql11_hosts
  become: true
  tasks:
    - name: setup pg 11
      shell: |
        rpm -Uvh https://yum.postgresql.org/11/redhat/rhel-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        yum install -y postgresql11-server postgresql11-contrib
    - name: initdb
      shell: |
        /usr/pgsql-11/bin/postgresql-11-setup initdb
      ignore_errors: yes
    - name: setup service
      shell: |
        systemctl enable postgresql-11.service
        systemctl start postgresql-11.service